---
# Variables (see defaults in defaults/main.yml):
#   - "RUSTUP_DIST_SERVER": URL of Rust dist server for toolchains.
#   - "RUSTUP_UPDATE_ROOT": URL of Rust rustup server.
- import_role:
    name: ansible-user-register

- name: Setup rustup
  shell: |
    rm -rf "{{ ansible_user_registered.home }}/.cargo"
    export RUSTUP_DIST_SERVER="{{ RUSTUP_DIST_SERVER }}"
    export RUSTUP_UPDATE_ROOT="{{ RUSTUP_UPDATE_ROOT }}"
    curl -o /tmp/rustup-init \
      ${RUSTUP_DIST_SERVER}/rustup/dist/x86_64-unknown-linux-gnu/rustup-init &&
      chmod +x /tmp/rustup-init &&
      /tmp/rustup-init -q -y --no-modify-path
  args:
    creates: "{{ ansible_user_registered.home }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo"

- name: Install additional rustup components
  shell: |
    "{{ ansible_user_registered.home }}/.cargo/bin/rustup" component add rust-src rust-analyzer
  args:
    creates: "{{ ansible_user_registered.home }}/.cargo/bin/rust-analyzer"

- name: "Install rustup targets"
  shell: |
    "{{ ansible_user_registered.home }}/.cargo/bin/rustup" target add "{{ item }}"
  args:
    creates: "{{ ansible_user_registered.home }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/{{ item }}"
  loop:
    - x86_64-unknown-linux-musl
    - x86_64-pc-windows-gnu
