---
# Variables (see defaults in defaults/main.yml):
#   - "RUSTUP_DIST_SERVER": URL of Rust dist server for toolchains.
#   - "RUSTUP_UPDATE_ROOT": URL of Rust rustup server.
- import_role:
    name: ansible-user-register

- import_tasks: tasks/extracted.yml
