#!/bin/sh
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ack \
  alien \
  apt-doc \
  apt-show-source \
  apt-show-versions \
  apt-utils \
  audacity \
  autofs \
  autokey-gtk \
  automake \
  autopoint \
  binutils-mipsel-linux-gnu \
  bmake \
  brasero \
  build-essential \
  bzip2 \
  cdecl \
  cifs-utils \
  clang \
  clang-14-doc \
  clangd \
  clang-format \
  clang-tidy \
  clang-tools \
  cmake \
  colordiff \
  curl \
  ddd \
  devede \
  doxygen \
  doxygen-doc \
  evince \
  exiftool \
  fd-find \
  ffmpeg \
  fonts-dejavu \
  fonts-hack-ttf \
  fonts-inconsolata \
  g++-11-multilib \
  gcc-11-aarch64-linux-gnu \
  gcc-11-arm-linux-gnueabihf \
  gcc-11-multilib \
  gcc-11-powerpc-linux-gnu \
  gcc-mingw-w64-x86-64 \
  gdisk \
  geeqie \
  gimp \
  git \
  git-doc \
  git-gui \
  git-svn \
  glibc-doc \
  gnucash \
  gnucash-common \
  gnucash-docs \
  golang \
  gparted \
  gperf \
  graphviz \
  graphviz-doc \
  gscan2pdf \
  gthumb \
  gwenview \
  hdparm \
  help2man \
  html2text \
  imagemagick \
  inotify-tools \
  k3b \
  kate \
  kdiff3 \
  keepassxc \
  keychain \
  konqueror \
  konversation \
  kubuntu-desktop \
  kubuntu-restricted-extras \
  libboost-all-dev \
  liblz4-tool \
  libreoffice \
  libreoffice-math \
  libsane1 \
  libsane-common \
  libsane-dev \
  linux-headers-generic \
  linux-tools-generic \
  lshw \
  lshw-gtk \
  maelstrom \
  mailutils \
  make-doc \
  manpages-dev \
  manpages-posix-dev \
  meld \
  moreutils \
  mpg321 \
  mplayer \
  mplayer-gui \
  mscgen \
  musl-dev \
  musl-tools \
  mutt \
  myrepos \
  nautilus \
  nfs-common \
  nmap \
  okular \
  pandoc \
  perl-doc \
  perl-doc-html \
  pigz \
  pithos \
  pv \
  python3-dev \
  python3-doc \
  python3-gnucash \
  python3-pip \
  python3-tk \
  python3-venv \
  qgit \
  ripgrep \
  rpm2cpio \
  ruby \
  ruby-dev \
  sane-utils \
  scons \
  scons-doc \
  shellcheck \
  shfmt \
  silversearcher-ag \
  skanlite \
  smartmontools \
  socat \
  speedcrunch \
  sqlite3 \
  sqlite3-doc \
  sqlitebrowser \
  stress \
  subversion \
  texi2html \
  texinfo \
  thunderbird \
  tidy \
  tigervnc-standalone-server \
  tigervnc-viewer \
  tmux \
  tofrodos \
  traceroute \
  tree \
  ttf-bitstream-vera \
  ttf-mscorefonts-installer \
  universal-ctags \
  vim \
  vim \
  vim-gtk3 \
  vlc \
  wget \
  wireshark \
  wmctrl \
  xclip \
  xdotool \
  xsel \
  xterm \
  zstd \

