---
- name: Install apt-file
  package:
    name:
      - apt-file
  register: apt_file
  when: ansible_distribution == 'Ubuntu'

- name: Update apt-file
  command: apt-file update
  when: ansible_distribution == 'Ubuntu' and apt_file is changed
- name: Install apt-rdepends
  package:
    name:
      - apt-rdepends
  when: ansible_distribution == 'Ubuntu'
- name: pipxg Install ansible
  shell: pipxg install --include-deps ansible && pipxg inject ansible passlib
  args:
    creates: /usr/local/bin/ansible
- name: Create Firefox policies directory
  file:
    path: /etc/firefox/policies/policies.json
    state: directory
    mode: 0755
- name: Disable automatic Firefox updates
  copy:
    dest: /etc/firefox/policies/policies.json
    src: firefox-policies.json
- name: Disable execution for motd files
  file:
    path: "{{ item }}"
    mode: -x
  loop:
    - "/etc/update-motd.d/10-help-text"
    - "/etc/update-motd.d/50-motd-news"
    - "/etc/update-motd.d/90-updates-available"
  when: ansible_distribution == 'Ubuntu'
- name: Uninstall landscape-common
  apt:
    name: landscape-common
    state: absent
- name: uvtoolg Install findx
  shell: uvtoolg install findx
  args:
    creates: /usr/local/bin/findx
- name: uvtoolg Install ptee
  shell: uvtoolg install ptee
  args:
    creates: /usr/local/bin/ptee
- name: Make symlinks for `unix2dos`/`dos2unix`
  file:
    src: "/usr/bin/{{ item.src_name }}"
    dest: "/usr/local/bin/{{ item.dest_name }}"
    state: link
  loop:
    - src_name: todos
      dest_name: unix2dos
    - src_name: fromdos
      dest_name: dos2unix
- name: uvtoolg Install cookiecutter
  shell: uvtoolg install cookiecutter
  args:
    creates: /usr/local/bin/cookiecutter
- name: uvtoolg Install svnwrap
  shell: uvtoolg install svnwrap
  args:
    creates: /usr/local/bin/svnwrap
- name: uvtoolg Install compiledb
  shell: uvtoolg install compiledb
  args:
    creates: /usr/local/bin/compiledb
- name: uvtoolg Install ipython
  shell: uvtoolg install ipython
  args:
    creates: /usr/local/bin/ipython
- name: uvtoolg Install poetry
  shell: uvtoolg install poetry --with poetry-plugin-export
  args:
    creates: /usr/local/bin/poetry
- name: uvtoolg Install pytest
  shell: uvtoolg install pytest
  args:
    creates: /usr/local/bin/pytest
- name: uvtoolg Install mypy
  shell: uvtoolg install mypy
  args:
    creates: /usr/local/bin/mypy
- name: uvtoolg Install ruff
  shell: uvtoolg install ruff
  args:
    creates: /usr/local/bin/ruff
- name: uvtoolg Install flake8-to-ruff
  shell: uvtoolg install flake8-to-ruff
  args:
    creates: /usr/local/bin/flake8-to-ruff
- name: uvtoolg Install flake8
  shell: uvtoolg install flake8 --with flake8-quotes,pep8-naming
  args:
    creates: /usr/local/bin/flake8
- name: uvtoolg Install black
  shell: uvtoolg install black
  args:
    creates: /usr/local/bin/black
- name: uvtoolg Install python-lsp-server
  shell: uvtoolg install python-lsp-server --with pylsp-mypy,python-lsp-ruff
  args:
    creates: /usr/local/bin/pylsp
- name: uvtoolg Install pyupgrade
  shell: uvtoolg install pyupgrade
  args:
    creates: /usr/local/bin/pyupgrade
- name: uvtoolg Install sphinx
  shell: uvtoolg install sphinx
  args:
    creates: /usr/local/bin/sphinx-quickstart
- name: uvtoolg Install docutils
  shell: uvtoolg install docutils --with pygments
  args:
    creates: /usr/local/bin/rst2html
- name: uvtoolg Install rstcheck
  shell: uvtoolg install rstcheck
  args:
    creates: /usr/local/bin/rstcheck
