---
- name: Install apt-file
  package:
    name:
      - apt-file
  register: apt_file
  when: ansible_distribution == 'Ubuntu'

- name: Update apt-file
  command: apt-file update
  when: ansible_distribution == 'Ubuntu' and apt_file is changed
- name: Install apt-rdepends
  package:
    name:
      - apt-rdepends
  when: ansible_distribution == 'Ubuntu'
- name: pipxg Install ansible
  shell: pipxg install --include-deps ansible && pipxg inject ansible passlib
  args:
    creates: /usr/local/bin/ansible
- name: Create Firefox policies directory
  file:
    path: /etc/firefox/policies/policies.json
    state: directory
    mode: 0755
- name: Disable automatic Firefox updates
  copy:
    dest: /etc/firefox/policies/policies.json
    src: firefox-policies.json
- name: Disable execution for motd files
  file:
    path: "{{ item }}"
    mode: -x
  loop:
    - "/etc/update-motd.d/10-help-text"
    - "/etc/update-motd.d/50-motd-news"
    - "/etc/update-motd.d/90-updates-available"
  when: ansible_distribution == 'Ubuntu'
- name: Uninstall landscape-common
  apt:
    name: landscape-common
    state: absent
- name: pipxg Install findx
  shell: pipxg install findx
  args:
    creates: /usr/local/bin/findx
- name: pipxg Install ptee
  shell: pipxg install ptee
  args:
    creates: /usr/local/bin/ptee
- name: Make symlinks for `unix2dos`/`dos2unix`
  file:
    src: "/usr/bin/{{ item.src_name }}"
    dest: "/usr/local/bin/{{ item.dest_name }}"
    state: link
  loop:
    - src_name: todos
      dest_name: unix2dos
    - src_name: fromdos
      dest_name: dos2unix
- name: pipxg Install cookiecutter
  shell: pipxg install cookiecutter
  args:
    creates: /usr/local/bin/cookiecutter
- name: pipxg Install svnwrap
  shell: pipxg install svnwrap
  args:
    creates: /usr/local/bin/svnwrap
- name: pipxg Install compiledb
  shell: pipxg install compiledb
  args:
    creates: /usr/local/bin/compiledb
- name: pipxg Install ipython
  shell: pipxg install ipython
  args:
    creates: /usr/local/bin/ipython
- name: pipxg Install poetry
  shell: pipxg install poetry && pipxg inject poetry poetry-plugin-export
  args:
    creates: /usr/local/bin/poetry
- name: pipxg Install pytest
  shell: pipxg install pytest
  args:
    creates: /usr/local/bin/pytest
- name: pipxg Install mypy
  shell: pipxg install mypy
  args:
    creates: /usr/local/bin/mypy
- name: pipxg Install ruff
  shell: pipxg install ruff
  args:
    creates: /usr/local/bin/ruff
- name: pipxg Install flake8-to-ruff
  shell: pipxg install flake8-to-ruff
  args:
    creates: /usr/local/bin/flake8-to-ruff
- name: pipxg Install flake8
  shell: pipxg install flake8 && pipxg inject flake8 flake8-quotes pep8-naming
  args:
    creates: /usr/local/bin/flake8
- name: pipxg Install black
  shell: pipxg install black
  args:
    creates: /usr/local/bin/black
- name: pipxg Install python-lsp-server[mccabe,pycodestyle,pydocstyle,pyflakes,rope]
  shell: pipxg install 'python-lsp-server[mccabe,pycodestyle,pydocstyle,pyflakes,rope]'
    && pipxg inject python-lsp-server python-lsp-black && pipxg inject python-lsp-server
    pylsp-mypy && pipxg inject python-lsp-server python-lsp-ruff
  args:
    creates: /usr/local/bin/pylsp
- name: pipxg Install pyupgrade
  shell: pipxg install pyupgrade
  args:
    creates: /usr/local/bin/pyupgrade
- name: pipxg Install sphinx
  shell: pipxg install sphinx
  args:
    creates: /usr/local/bin/sphinx-quickstart
- name: pipxg Install docutils
  shell: pipxg install docutils && pipxg inject docutils pygments
  args:
    creates: /usr/local/bin/rst2html
- name: pipxg Install rstcheck
  shell: pipxg install rstcheck
  args:
    creates: /usr/local/bin/rstcheck
