---
- name: Install ubuntu `:role:workstation` packages
  package:
    name:
    - apt-doc
    - apt-show-source
    - apt-show-versions
    - apt-utils
    - python3-venv
    - python3-pip
    - kubuntu-desktop
    - kubuntu-restricted-extras
    - keychain
    - wmctrl
    - xdotool
    - xclip
    - xsel
    - autokey-gtk
    - fonts-inconsolata
    - ttf-bitstream-vera
    - fonts-dejavu
    - fonts-hack-ttf
    - ttf-mscorefonts-installer
    - tmux
    - nautilus
    - konqueror
    - mutt
    - mailutils
    - ripgrep
    - ack
    - silversearcher-ag
    - meld
    - kdiff3
    - colordiff
    - inotify-tools
    - lshw
    - lshw-gtk
    - smartmontools
    - hdparm
    - pigz
    - liblz4-tool
    - zstd
    - pv
    - tofrodos
    - tree
    - stress
    - moreutils
    - socat
    - traceroute
    - nmap
    - wireshark
    - git-doc
    - git-svn
    - git-gui
    - qgit
    - build-essential
    - linux-headers-generic
    - cmake
    - ddd
    - automake
    - autopoint
    - make-doc
    - manpages-dev
    - texinfo
    - texi2html
    - scons
    - scons-doc
    - glibc-doc
    - clang
    - clang-format
    - clang-tidy
    - clang-tools
    - clangd
    - clang-14-doc
    - universal-ctags
    - gcc-11-multilib
    - g++-11-multilib
    - bmake
    - rpm2cpio
    - alien
    - cdecl
    - sqlite3
    - sqlite3-doc
    - sqlitebrowser
    - html2text
    - linux-tools-generic
    - manpages-posix-dev
    - gcc-mingw-w64-x86-64
    - gperf
    - help2man
    - gcc-11-powerpc-linux-gnu
    - gcc-11-arm-linux-gnueabihf
    - gcc-11-aarch64-linux-gnu
    - binutils-mipsel-linux-gnu
    - vim
    - vim-gtk
    - universal-ctags
    - ruby
    - ruby-dev
    - kate
    - python3-dev
    - python3-doc
    - python3-tk
    - shellcheck
    - perl-doc
    - perl-doc-html
    - doxygen
    - doxygen-doc
    - graphviz
    - graphviz-doc
    - mscgen
    - golang
    - pandoc
    - tidy
    - html2text
    - exiftool
    - okular
    - evince
    - geeqie
    - imagemagick
    - speedcrunch
