---
- name: Ensure Firewall configuration file exists
  file:
    path: /etc/pve/firewall/cluster.fw
    state: touch
    owner: root
    group: www-data
    mode: 'u=rw,g=r'
- name: Ensure `OPTIONS` section in firewall configuration file
  lineinfile:
    path: /etc/pve/firewall/cluster.fw
    line: '[OPTIONS]'
- name: Ensure firewall is enabled
  lineinfile:
    path: /etc/pve/firewall/cluster.fw
    insertafter: '^\[OPTIONS\]'
    regexp: '^\s*enable\s*:'
    line: 'enable: 1'
- name: Ensure `RULES` section in firewall configuration
  lineinfile:
    path: /etc/pve/firewall/cluster.fw
    line: '[RULES]'
- name: Restart firewall
  shell: |
    pve-firewall restart
