---
- name: Create and backup default ipython profile
  shell: |
    ipython profile create
    cp "{{ ansible_user_registered.home }}/.ipython/profile_default/ipython_config.py" "{{ ansible_user_registered.home }}/.ipython/profile_default/ipython_config.py.dist"
  args:
    creates: "{{ ansible_user_registered.home }}/.ipython/profile_default/ipython_config.py"
- name: Disable ipython confirm_exit
  lineinfile:
    dest: "{{ ansible_user_registered.home }}/.ipython/profile_default/ipython_config.py"
    regexp: '^#?\s*c\.TerminalInteractiveShell\.confirm_exit\b.*'
    line: 'c.TerminalInteractiveShell.confirm_exit = False'
