---
- name: Lock down lockd port
  ini_file:
    path: /etc/nfs.conf
    section: lockd
    option: port
    value: 2045
- name: Lock down lockd udp-port
  ini_file:
    path: /etc/nfs.conf
    section: lockd
    option: udp-port
    value: 2045
- name: Lock down statd port
  ini_file:
    path: /etc/nfs.conf
    section: statd
    option: port
    value: 2046
- name: Lock down statd udp-port
  ini_file:
    path: /etc/nfs.conf
    section: statd
    option: outgoing-port
    value: 2047
- name: Lock down mountd port
  ini_file:
    path: /etc/nfs.conf
    section: mountd
    option: port
    value: 2048
- name: Setup exports
  lineinfile:
    dest: /etc/exports
    line: '/m      192.168.254.0/24(rw,insecure,async,no_root_squash,no_subtree_check)'
- name: Restart NFS server
  shell: |
    systemctl restart nfs-kernel-server rpc-statd.service
- name: Add firewall rules
  lineinfile:
    path: /etc/pve/firewall/cluster.fw
    insertafter: '^\[RULES\]'
    line: "{{ item }}"
  loop:
    - IN ACCEPT -p udp -dport 2049 -log nolog # nfs
    - IN ACCEPT -p tcp -dport 2049 -log nolog # nfs
    - IN ACCEPT -p udp -dport 2048 -log nolog # mountd
    - IN ACCEPT -p tcp -dport 2048 -log nolog # mountd
    - IN ACCEPT -p udp -dport 2046 -log nolog # statd
    - IN ACCEPT -p tcp -dport 2046 -log nolog # statd
    - IN ACCEPT -p udp -dport 2045 -log nolog # nlockmgr
    - IN ACCEPT -p tcp -dport 2045 -log nolog # nlockmgr
    - IN ACCEPT -p udp -dport 111 -log nolog # sunrpc
    - IN ACCEPT -p tcp -dport 111 -log nolog # sunrpc
- name: Restart firewall
  shell: |
    pve-firewall restart
