---
- name: Acquire mozillateam PPA key
  shell: |
    gpg \
      --homedir /tmp \
      --no-default-keyring \
      --keyserver keyserver.ubuntu.com \
      --recv-keys \
      --keyring /etc/apt/keyrings/mozillateam.gpg \
      0AB215679C571D1C8325275B9BDB3D89CE49EC21
  args:
    creates: /etc/apt/keyrings/mozillateam.gpg
- name: Create mozillateam.sources
  shell: |
      printf "%s\n" \
        "Types: deb" \
        "URIs: https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/" \
        "Suites: $(lsb_release -cs)" \
        "Components: main" \
        "Architectures: $(dpkg --print-architecture)" \
        "Signed-By: /etc/apt/keyrings/mozillateam.gpg" \
        > /etc/apt/sources.list.d/mozillateam.sources
  args:
    creates: /etc/apt/sources.list.d/mozillateam.sources
- name: Update APT cache
  apt:
    update_cache: yes
- name: Boost Firefox priority to ensure it comes from Mozilla PPA
  copy:
    dest: /etc/apt/preferences.d/mozillateamppa-firefox
    content: |
      Package: firefox*
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 501
- name: Boost Thunderbird priority to ensure it comes from Mozilla PPA
  copy:
    dest: /etc/apt/preferences.d/mozillateamppa-thunderbird
    content: |
      Package: thunderbird*
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 501
- name: Install Firefox from Mozilla PPA
  apt:
    name: firefox
