---
- hosts: all
  become: yes
  tasks:
    - import_role:
        name: force-limit-switch

    - import_role:
        name: firefox-tarball
      vars:
        - FIREFOX_VERSION: 104.0.2
        - FIREFOX_LOCAL_DIR: "{{ lookup('env', 'HOME') }}/path/to/firefox"
