---
- hosts: all
  become: yes
  tasks:
    - import_role:
        name: force-limit-switch

    - import_role:
        name: home

    - import_role:
        name: docker
      vars:
        DOCKER_USER: "mike"

    - import_role:
        name: home-golang
