---
- hosts: all
  become: yes
  vars_prompt:
    - name: shared_password
      prompt: "Enter shared password for some_user, root"

  tasks:
    - import_role:
        name: force-limit-switch

    - name: Set passwords
      user:
        name: "{{ item }}"
        password: "{{ shared_password | password_hash('sha512', 'nacl')}}"
      loop:
        - some_user
        - root
