---
- hosts: all
  become: yes
  vars_prompt:
    - name: password
      prompt: "Enter password for root"

  tasks:
    - import_role:
        name: force-limit-switch

    - name: Set root password
      user:
        name: root
        password: "{{ password | password_hash('sha512', 'nacl')}}"
