---
- hosts: all
  become: yes
  vars_prompt:
    - name: password
      prompt: "Enter password for some_user"

  tasks:
    - import_role:
        name: force-limit-switch

    - name: Set some_user password
      user:
        name: some_user
        password: "{{ password | password_hash('sha512', 'nacl')}}"
