---
- name: Disable automounting
  command:
    gsettings set org.gnome.desktop.media-handling automount false

- name: Uninstall unattended-upgrades
  apt:
    name:
      - debootstrap
      - gdisk
      - zfsutils-linux
    cache_valid_time: 3600

- name: Disable zfs-zed
  service:
    name: zfs-zed
    enabled: no
    state: stopped
