---
- name: Disable systemd-networkd-wait-online
  service:
    name: systemd-networkd-wait-online
    state: stopped
    enabled: no
  when: ansible_distribution == 'Ubuntu'
- name: ufw deny 5355/udp (multicast DNS for Windows)
  ufw:
    rule: deny
    proto: udp
    port: '5355'
    comment: Block Windows multicast DNS
  when: ansible_distribution == 'Ubuntu'
- name: Enable Ubuntu 24+ source repositories
  lineinfile:
    dest: /etc/apt/sources.list.d/ubuntu.sources
    regexp: '^Types: deb$'
    line: 'Types: deb deb-src'
  register: ubuntu_sources
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 24

- name: Update APT cache for deb-src
  apt:
    update_cache: yes
  when: ubuntu_sources is changed
- name: Setup ssh config defaults
  copy:
    dest: /etc/ssh/ssh_config.d/90-general.conf
    src: ssh_config.d-90-general.conf
    mode: "u=rw,go=r"
