---
- name: Install echod
  copy:
    src: echod
    dest: /usr/local/bin/echod
    owner: root
    group: root
    mode: 0755
- name: Disable systemd-networkd-wait-online
  service:
    name: systemd-networkd-wait-online
    state: stopped
    enabled: no
  when: ansible_distribution == 'Ubuntu'
- name: Set timezone
  command: timedatectl set-timezone America/New_York
- name: ufw deny 5355/udp (multicast DNS for Windows)
  ufw:
    rule: deny
    proto: udp
    port: '5355'
    comment: Block Windows multicast DNS
  when: ansible_distribution == 'Ubuntu'
- name: Enable Ubuntu 24+ source repositories
  lineinfile:
    dest: /etc/apt/sources.list.d/ubuntu.sources
    regexp: '^Types: deb$'
    line: 'Types: deb deb-src'
  register: ubuntu_sources
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 24

- name: Update APT cache for deb-src
  apt:
    update_cache: yes
  when: ubuntu_sources is changed
- name: Setup ssh config defaults
  copy:
    dest: /etc/ssh/ssh_config.d/90-general.conf
    src: ssh_config.d-90-general.conf
    mode: "u=rw,go=r"
- name: Disable X11 forwarding for Github
  copy:
    dest: /etc/ssh/ssh_config.d/10-github.conf
    src: ssh_config.d-10-github.conf
    mode: "u=rw,go=r"
- name: Setup ssh server environment variable propagation
  copy:
    dest: /etc/ssh/sshd_config.d/90-accept-env.conf
    src: sshd_config.d-90-accept-env.conf
    mode: "u=rw,go=r"
- name: Do not hide Grub
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_TIMEOUT_STYLE'
    line: '#GRUB_TIMEOUT_STYLE'
  register: ubuntu_grub_configuration1
  when: ansible_distribution == 'Ubuntu'

- name: Adjust Grub timeout
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_TIMEOUT=.*'
    line: 'GRUB_TIMEOUT=2'
  register: ubuntu_grub_configuration2
  when: ansible_distribution == 'Ubuntu'

- name: Update grub for new configuration
  command:
    update-grub
  when: ubuntu_grub_configuration1 is changed or ubuntu_grub_configuration2 is changed
- name: Setup SHELL in /etc/crontab
  lineinfile:
    path: /etc/crontab
    regexp: '^SHELL=.*'
    line: 'SHELL=/bin/bash'
- name: Setup MAILTO in /etc/crontab
  lineinfile:
    path: /etc/crontab
    regexp: '^MAILTO=.*'
    insertbefore: '^SHELL=.*'
    line: 'MAILTO=root'
