---
- name: Install fedora `:role:base` packages
  package:
    name:
    - autofs
    - cifs-utils
    - curl
    - git
    - keychain
    - myrepos
    - nfs-utils
    - subversion
    - vim
    - wget
