---
- name: Install Google signing key
  shell: |
    curl -fsSL https://dl.google.com/linux/linux_signing_key.pub |
      gpg --dearmor -o /etc/apt/keyrings/google-chrome.gpg
  args:
    creates: /etc/apt/keyrings/google-chrome.gpg
  when: ansible_facts['distribution'] == 'Ubuntu'
- name: Create /etc/apt/sources.list.d/google-chrome.sources
  shell: 'printf "%s\n"  "### THIS FILE IS AUTOMATICALLY CONFIGURED ###"  "# Changes
    to this file will not be preserved."  "# This file will not be recreated if removed."  "X-Repolib-Name:
    Google Chrome"  "Types: deb"  "URIs: https://dl.google.com/linux/chrome-stable/deb/"  "Suites:
    stable"  "Components: main"  "Signed-By: /usr/share/keyrings/google-chrome.gpg"  >
    /etc/apt/sources.list.d/google-chrome.sources'
  args:
    creates: /etc/apt/sources.list.d/google-chrome.sources
- name: Update APT cache
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
- name: Install Google Chrome stable version
  package:
    name:
    - google-chrome-stable
  when: ansible_facts['distribution'] == 'Ubuntu'
