---
- name: Uninstall unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
- name: Disable apt-daily-related services
  # Essentially, this is::
  #   systemctl disable apt-daily{,-upgrade}.{service,timer}
  #   systemctl stop apt-daily{,-upgrade}.{service,timer}
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - apt-daily.service
    - apt-daily.timer
    - apt-daily-upgrade.service
    - apt-daily-upgrade.timer
